apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: eu-central-1
  version: "1.24"
availabilityZones:
- eu-central-1a
- eu-central-1b
- eu-central-1c
managedNodeGroups:
- name: ng-1
  privateNetworking: true
  instanceType: t3.large
  amiFamily: Bottlerocket
  minSize: 2
  maxSize: 5
  desiredCapacity: 3
  volumeSize: 20
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  withOIDC: true
addons:
- name: vpc-cni
  version: latest
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
